### ISSUE TITLE
Need to add autofill button in three forms of same page

### ISSUE THREAD

**Issue by chandru1822** [humbertodias/js-linkedin-auto-fill-form#1]
I want to add autofill button in three forms of same page. I added the below code in each form by the changing the atrribute value. Their attribute value is that particular element Id. Now, the problem is all three sigin button is appearing in first form itself.I added the below script in each form by changing the Please suggest the solution to resolve this,

![talentica](https://user-images.githubusercontent.com/24269236/33977585-a09431fe-e0c1-11e7-979b-8f4b218583f0.PNG)

<script src="https://www.linkedin.com/autofill/js/autofill.js" type="text/javascript" async></script>
<script type="IN/Form2" data-form="form-validate-business" data-field-firstname="fname" data-field-lastname="lname" data-field-phone="phone-number" data-field-email="email"></script>

**Comment by humbertodias** [comment]
Check it out  the follow steps 
https://www.linkedin.com/help/lms/answer/65688/linkedin-autofill-setup-guide?lang=en

Demo
https://business.linkedin.com/marketing-solutions/cx/17/02/the-sophisticated-marketers-guide-to-linkedin

**Comment by chandru1822** [comment]
I am facing the problem when i add the linkedin autofill  in same page but in different tabs.

**Comment by humbertodias** [comment]
Maybe you had to use a whitelisted domain, otherwise, it will not work.

--
Send your LinkedIn representative a list of domains and subdomains where you will be placing the AutoFill code to whitelist your domains. Please include "http", "https", and "www" in your domain and subdomain URLs.
Example: https://www.linkedin.com/groups

Note: AutoFill will not work until your domains have been whitelisted.

**Comment by chandru1822** [comment]
The Domain is whitelisted already.

**Comment by humbertodias** [comment]
I've made an update. Try again.
https://github.com/humbertodias/js-linkedin-auto-fill-form/blob/master/doc/demo.mp4?raw=true

Thank you

**Comment by harithm918** [comment]
![image](https://github.com/humbertodias/js-linkedin-auto-fill-form/assets/13028171/c6ffac7f-2292-488b-9c13-e471d9a62cc1)

I found this issue. can anyone help me to solve this
